# Generated by Django 4.0.3 on 2022-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_title', models.CharField(max_length=100, null=True)),
                ('search_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'search',
            },
        ),
    ]
